Proyecto/Blog/urls.py
from django.conf.urls import url

from . import views


app_name= 'appJM'
urlpatterns = [ 
	url(r'^$', views.ListadoHome.as_view(), name = 'home'),
	url(r'^entrada/(?P<pk>.*)$', views.VistaEntradaCompleta.as_view(), name='VistaEntradaCompleta'),
	url(r'^sobreMi/$', views.VistaSobreMi.as_view(), name = 'sobreMi'),
	url(r'^crear/$', views.VistaCrearEntrada.as_view(), name = 'crear'),
	url(r'^editar/(?P<pk>.*)$', views.VistaEntradaActualizar.as_view(), name= 'editar'),
	url(r'^eliminar/(?P<pk>.*)$', views.VistaEntradaEliminar.as_view(), name= 'eliminar'),
	url(r'^registro/$', views.newUser, name = 'registro'),
	url(r'^login/$', views.acceso, name = 'login'),
	url(r'^logout/$', views.VistaLogout, name = 'logout'),
	url(r'^comentario/(?P<pk>.*)$', views.comentario, name = 'comentario'),
	]

Proyecto/ProyectoJM/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from Blog import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('Blog.urls', namespace='home')),
]

Proyecto/Blog/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.

class Entrada(models.Model):
	titulo = models.CharField(max_length = 100)
	cuerpo = models.TextField()
	fecha = models.DateTimeField(default = datetime.now, blank=True)

	def __str__(self):
			return self.titulo


class Comentario(models.Model):
		date = models.DateTimeField(default= datetime.now)
		author = models.ForeignKey(User)
		Texto_Comentario = models.TextField()
		id_message = models.ForeignKey(Entrada)

		def __str__(self):
			return "%s %s " % (self.id_message, self.Texto_Comentario[:60])

class UserProfile(models.Model):
	usuario = models.OneToOneField(settings.AUTH_USER_MODEL)

	def __unicode__(self):
		return self.usuario.username

Proyecto/Blog/forms.py
from django import forms
from .models import Comentario

class ComentForm(forms.ModelForm):
	Texto_Comentario = forms.CharField(widget=forms.Textarea)

	class Meta:
		model = Comentario
		fields = ('Texto_Comentario',)

Proyecto/Blog/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Para formularios:
from django.forms import ModelForm
from .forms import ComentForm
#from django.core.context_processors import csrf #--> para versiones < django 1.10
from django.views.decorators import csrf

from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from datetime import datetime
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from Blog.models import Entrada, UserProfile, Comentario
# Create your views here.

def ListadoTitulos():
    listadoTitulos = Entrada.objects.all()[:10]
    return listadoTitulos


class ListadoHome(ListView):
	context_object_name = 'listadoEntradas'
	model = Entrada
	template_name = 'home.html'
	paginate_by = 4	#cuatro objetos por pagina

 	# En este formato, las palabras se acortan en el html con entrada.cuerpo|slice:":140"
	def get_context_data(self, **kwargs):
		context = super(ListadoHome, self).get_context_data(**kwargs)
		context['listadoTitulos'] = ListadoTitulos()
		return context

class VistaEntradaCompleta(DetailView):
	model = Entrada
	template_name = 'entradaCompleta.html'
	

	def get_context_data(self, **kwargs):
		context = super(VistaEntradaCompleta, self).get_context_data(**kwargs)
		context['listadoTitulos'] = ListadoTitulos()
		context['listadoComentarios'] = Comentario.objects.filter(id_message=self.kwargs['pk'])
		return context


class VistaSobreMi(TemplateView):
	template_name = 'sobreMi.html'

	def get_context_data(self, **kwargs):
		context = super(VistaSobreMi, self).get_context_data(**kwargs)
		context['listadoTitulos'] = ListadoTitulos()
		return context

class VistaCrearEntrada(CreateView):
	template_name = 'entradaForm.html'
	model = Entrada
	fields = ('titulo', 'cuerpo')
	success_url = '/' 

	def get_context_data(self, **kwargs):
		# Obtenemos el contexto de la clase base
		context = super(VistaCrearEntrada, self).get_context_data(**kwargs)
		# anyadimos nuevas variables de contexto al diccionario
		context['titulo'] = 'Crear articulo'
		context['nombre_btn'] = 'Crear'
		context['listadoTitulos'] = ListadoTitulos()
		# devolvemos el contexto
		return context

	def dispatch(self, request, *args, **kwargs):
		# obtenemos el contexto de la calse base
		# si no los tiene lo redirecciona a login 
		if not request.user.has_perms('blog.add_entrada'):
			return redirect(settings.LOGIN_URL)
		return super(VistaCrearEntrada, self).dispatch(request, *args, **kwargs)

	#def form_valid(self, form):
	#	messages.success(self.request, 'Entrada enviada correctamente')
	#	return super(VistaCrearEntrada, self).form_valid(form)


class VistaEntradaActualizar(UpdateView):
	template_name = 'entradaForm.html'
	model = Entrada
	fields = ('titulo', 'cuerpo')
	success_url = '/'

	def get_context_data(self, **kwargs):	
		# Obtenemos el contexto de la clase base
		context = super(VistaEntradaActualizar, self).get_context_data(**kwargs)
	    	# anyadimos nuevas variables de contexto al diccionario
		context['title'] = 'Editar articulo'
		context['nombre_btn'] = 'Editar'
		context['listadoTitulos'] = ListadoTitulos()
		# devolvemos el contexto
		return context

	def dispatch(self, request, *args, **kwargs):
    		if not request.user.has_perms('blog.change_entrada'):
        		return redirect(settigns.LOGIN_URL)
    		return super(VistaEntradaActualizar, self).dispatch(request, *args, **kwargs)

class VistaEntradaEliminar(DeleteView):
    template_name = 'confirmarEliminacion.html'
    success_url = '/'
    model = Entrada

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perms('blog.delete_entrada'):
            return redirect(settings.LOGIN_URL)
        return super(VistaEntradaEliminar, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(VistaEntradaEliminar, self).get_context_data(**kwargs)
        context['listadoTitulos'] = ListadoTitulos()
        # devolvemos el contexto
        return context


def comentario(request, pk):
	if  request.user.is_authenticated():
		if request.method == 'POST':
			form = ComentForm(request.POST)
			if form.is_valid():
				coment = form.save(commit=False)
				coment.author = request.user
				coment.published_date = datetime.now()
				coment.id_message = Entrada.objects.get(pk=pk)
				coment.save()
				return redirect('home:VistaEntradaCompleta', pk=pk)
		else:
			form = ComentForm()
		return render(request, 'comentario.html', {'form':form, 'listadoTitulos': ListadoTitulos()})
	else:
		return redirect('home:login')

###########################################################################################
##									USUARIO

def newUser(request):
	if request.method == 'POST':
		form=UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			usuario = User.objects.get(username=form.cleaned_data['username'])
			user = UserProfile(usuario=usuario)
			user.save()
			return render(request, 'gracias.html', {'usuario': usuario})
	else:
		#si el method es GET, instanciamos un objeto RegistroUsuario vacio
		form=UserCreationForm()
	# Y mostramos los datos
	return render(request, 'registro.html', {'form':form, 'listadoTitulos': ListadoTitulos})



def acceso(request):
	if  request.user.is_authenticated():
		return redirect('/')
	mensaje=''
	if request.method == 'POST':
		form = AuthenticationForm(request.POST)
		if form.is_valid:
			usuario = request.POST['username']
			password=request.POST['password']
			acceso=authenticate(username=usuario, password=password)
			if acceso is not None:
				if acceso.is_active:
					login(request, acceso)
					return redirect('/')
				else:
					return render(request, 'no_activo.html')
			else:
				return render(request, 'no_usuario.html')
	else:
		form = AuthenticationForm()
	return render(request, 'login.html', {'form': form, 'listadoTitulos': ListadoTitulos})

@login_required(login_url= 'login')
def VistaLogout(request):
	logout(request)
	return render(request, 'logout.html', {'listadoTitulos': ListadoTitulos})

	

Proyecto/Blog/templates/_menuLateral.html
{% block lateral %}
          <div>
            <h3>Últimas entradas</h4>
            {% if listadoTitulos %}
              <ul>
                {% for x in listadoTitulos %}
                  <li><small><a href="{% url 'appJM:VistaEntradaCompleta' x.id %}">
                     {{ x.titulo }}</a></small></li>
                {% endfor %}
              </ul>
            {% else %}
              <h4>Sin entradas</h4>
              <p>La base de datos por el momento no tiene entradas. Por favor, introduzca al menos una para poder contemplarla</p>
            {% endif %}

          </div>
{% endblock lateral%}

Proyecto/Blog/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="es">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

	<title>Blog de Juan Miguel Alba</title>
</head>
<body>
    <nav class="navbar navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home:home' %}">Blog de Juan Miguel Alba</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% url 'home:home' as home_url %}
            {% url 'home:sobreMi' as sobreMi_url %}
            {% url 'home:crear' as crear_url %}
            {% url 'home:editar' as editar_url %}
            {% url 'home:VistaEntradaCompleta' as vistaDetalle_url %}

            <li {% if request.get_full_path == home_url %} class="active" {% endif %}><a href="{% url 'home:home' %}">Home</a></li>
            <li {% if request.get_full_path == sobreMi_url %} class="active" {% endif %}><a href="{% url 'home:sobreMi' %}">Sobre Mí</a></li>
            {% if perms.entrada.can_add %}
              <li {% if request.get_full_path == crear_url %} class="active" {% endif %}><a href="{% url 'home:crear' %}">Crear artículo</a></li>
            {% endif %}
          </ul>

          <!-- Parte derecha dedicada a los usuarios -->

            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                <li><h3>{{user.username}}</h3></li>
                <li {% if request.get_full_path == registro %} class="active" {% endif %}><a href="{% url 'home:logout' %}">Logout</a></li>
              {% else %}
                <li {% if request.get_full_path == registro %} class="active" {% endif %}><a href="{% url 'home:registro' %}">Registro</a></li>
                <li {% if request.get_full_path == login %} class="active" {% endif %}><a href="{% url 'home:login' %}">Login</a></li>
              {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

	<div class="container">
		
		<div class="starter-template"></div>
			<div class="row">
				<div class="col-md-9"> 

          <!-- Para la lista de entradas -->
					{% block content %}
					{% endblock %}

					{% block paginator %}
					{% endblock %}

				</div>
				<div class="col-md-3">
          {% block lateral %}
            {% include '_menuLateral.html' %}
          {% endblock lateral%}
				</div>
			</div> <!-- /.row-->
		</div>

	</div> <!-- /.container -->

</body>

<footer>
  <div class="container">
    <div class="row" style="padding: 20px 0;">
      <div class="col-md-4">
 
        <h4>Manuales seguidos</h4>
        <ul>
          <li><a href="https://docs.djangoproject.com/es/1.10/intro/tutorial01/">DjangoProject</a></li>
          <li><a href="http://www.w3schools.com/html/default.asp">Manual HTML</a></li>
          <li><a href="http://tutorial.djangogirls.org/es/">DjangoGirls</a></li>
        </ul>          
      </div>

      <div class="col-md-4">
        <h4>Software Necesario</h4>
        <ul>
          <li><a href="https://www.djangoproject.com/download/1.10/tarball/">Django 1.10</a></li>
          <li><a href="https://www.djangoproject.com/download/">Manual Instalación</a></li>
          <li><a href="https://www.python.org/downloads/">Python 2.7</a></li>
        </ul>          
      </div>

      <div class="col-md-4">
        <ul>
          <li class="naranja">SuperUsuarioAdmin: JuanmiAlba
          <li class="naranja">Contraseña: blog1234
        </ul>          
      </div>

    </div>
  </div><!-- /.container -->
  <div class="firma">
     ⓒ 2017 Juan Miguel Alba Jiménez
  </div>
</footer>

</html>

Proyecto/Blog/templates/comentario.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}
	<form method="POST" class="post-form">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-primary">Enviar comentario</button>
	</form>
{% endblock %}

Proyecto/Blog/templates/confirmarEliminacion.html
{% extends "base.html" %}

{% block content %}
 <h2 class="page-header">Confirmación para eliminar {{ entrada.titulo }}</h2>
    <form method="post" action="">
        {% csrf_token %}
        <p>¿Seguro que quieres eliminar la entrada {{ entrada.titulo }}?</p>
        <div class="row">
      		<div class="col-md-6">
	 	        <button type="submit" class="btn btn-danger">Si, eliminar</button>
		        <a href="{% url 'home:VistaEntradaCompleta' entrada.id %}" class="btn-jm" style="float:right">Cancelar</a>       			
        	</div>
        </div>
    </form>

{% endblock content %}

Proyecto/Blog/templates/entradaCompleta.html
{% extends "base.html" %}

{%block content%}

	<h1>{{ entrada.titulo }}</h1>
	<p> {{ entrada.cuerpo }}</p>
	<div class="fecha"> {{ entrada.fecha }}</div>
    {% if perms.article.can_change %}
		<a href="{% url 'home:editar' entrada.id %}" class="btn btn-primary">Editar</a>
    {% endif %}
    {% if perms.article.can_delete %}
    	<a href="{% url 'home:eliminar' entrada.id %}" class="btn btn-danger">Eliminar</a>
	{% endif %}

	<a href="{% url 'home:comentario' entrada.id %}" class="btn btn-primary">Comentar</a>

    {% if listadoComentarios %}
    <h3>Comentarios</h3>
		<ul>
			{% for comentario in listadoComentarios %}
				
				<h4>Usuario: {{ comentario.author }}</h4>
				<p>{{comentario.Texto_Comentario}}</p>
				<p>
	   				<small class="fecha">{{comentario.date}}</small>
				</p>
				<br>
			{% endfor %}
		</ul>
	{% else %}
		<h1>Sin Comentarios</h1>
		<p>La base de datos por el momento no tiene comentarios.</p>
	{% endif %}

{% endblock %}

Proyecto/Blog/templates/entradaForm.html
{% extends "base.html" %}

{% block content %}
    <h1 class="page-header">{{ titulo }}</h1>
    <form role="form" action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{{ nombre_btn }}</button>
    </form>
    
{% endblock content %}

Proyecto/Blog/templates/gracias.html
{% extends "base.html" %}

{% block content %}
<div class="alert alert-success">
  <strong>{{ usuario }} gracias por registarte!</strong> 
</div>
<a href="{% url 'appJM:login' %}"><button type="submit" class="btn btn-primary">Login</button></a>
	
{% endblock content %}

Proyecto/Blog/templates/home.html
{% extends "base.html" %}

{%block content%}

	{% if listadoEntradas %}
		<ul>
			{% for entrada in listadoEntradas %}
				<li><h2><a href="{% url 'appJM:VistaEntradaCompleta' entrada.id %}">
				   {{ entrada.titulo }}</a></h1></li>
				<p>{{entrada.cuerpo|slice:":140"}} ... </p>
				<p>
					<small><a href="{% url 'appJM:VistaEntradaCompleta' entrada.id %}" class="leerMas">
				   → leer +</a></small>
	   				<small class="fecha">{{entrada.fecha}}</small>
				</p>
				<br>
			{% endfor %}
		</ul>
	{% else %}
		<h1>Sin entradas</h1>
		<p>La base de datos por el momento no tiene entradas. Por favor, introduzca al menos una para poder contemplarla</p>
	{% endif %}

{% endblock %}


{% block paginator %}

	<center><p>
	{% if page_obj.has_previous %}
		<a href="?page={{ page_obj.previous_page_number }}" class="iconPageMasMenos">⧀</a> |
	{% endif %}
	
	<small>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</small>

	{% if page_obj.has_next %}
		| <a href="?page={{ page_obj.next_page_number }}" class="iconPageMasMenos"> ⧁</a>
	{% endif %}
	</p></center>

{% endblock %}

Proyecto/Blog/templates/login.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="page-header"><h2>Login</h2></div>
            {% if mensaje %}
                <div class="alert alert-danger">
                    {{ mensaje }}
                </div>
            {% endif %}

            <form method="post" action="">
                {% csrf_token %}
                <div class="form-group">
                    <label class="control-label" for="username">Nombre de usuario</label>
                    <input type="text" id="username" name="username" class="form-control" value="{{ username }}">
                </div>
                <div class="form-group">
                    <label for="password">Contraseña</label>
                    <input type="password" name="password" id="password" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
{% endblock content %}

Proyecto/Blog/templates/logout.html
{% extends "base.html" %}

{% block content %}
<div class="alert alert-success">
  <strong>Te has desconectado con exito!!</strong> 
</div>
	
{% endblock content %}

Proyecto/Blog/templates/no_activo.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}
<div class="alert alert-danger">
  <strong>El usuario no esta activo, contacte con el administrador para resolver el problema.</strong>
</div>

{% endblock %}

Proyecto/Blog/templates/no_usuario.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="alert alert-danger">
  <strong>Error en el login. El usuario y la contraseña no coinciden o no existen.</strong>
</div>
  <a href="{% url 'appJM:login' %}"><button type="button">Intentalo de nuevo</button></a>
{% endblock %}

Proyecto/Blog/templates/registro.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-sm-offset-3">
            <div class="page-header">
                <h2>Registro Usuario</h2>
            </div>

            <form method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Registrar</button>
            </form>
        </div>
    </div>
{% endblock %}

Proyecto/Blog/templates/sobreMi.html
{% extends "base.html" %}

{% block content %}
    <h2 class="page-header">Sobre mí</h2>
    <p>Estudiante de grado de ingeniería informatica.</p>
{% endblock content %}